#ifndef BIB_H
#define BIB_H
#include "iostream"
#include "QSqlQuery"
#include "QSqlDatabase"
#include "QDebug"
#include "string.h"
#include "ctime"
#include "QDate"
#include "QTableWidgetItem"
#include <QMediaPlayer>
#include "QMessageBox"
#include "string"
#include <QtNetwork/QAbstractSocket>
#include <QtNetwork/QSslSocket>
#include <QString>
#include <QTextStream>
#include <QDebug>
#include <QtWidgets/QMessageBox>
#include <QByteArray>
#include <QFile>
#include <QFileInfo>
#endif // BIB_H
